### PR TITLE
Change from deprecated cl library to non-deprecated cl-lib.

### LINKED ISSUE #90: Package cl is deprecated in 27
Package `cl` is deprecated in 27. Should use `cl-lib` instead.

### PR DESCRIPTION
**Pull request by pierre-rouleau**
Should fix #90.

### CODE REVIEW

**Comment by suntong** [comment]
@pierre-rouleau, the https://github.com/gregsexton/origami.el seems to be in unmaintained stage. 

Hope you take over the maintenance, and publish to elpa someday (fixing https://github.com/gregsexton/origami.el/issues/105)

**Comment by pierre-rouleau** [comment]
@suntong I am pretty busy these days and have not yet read the complete origami code.  I wouldn't mind doing it, but probably not for a little while.  Besides, my system allows me to pick any package from published Git repo and install it inside a separate directory.  So unlike elpa based distribution of packages that does not suffer from increasing the number of directories in Emacs' load-path.   I have yet to see the advantage of storing each package in a separate directory when all packages are supposed to use different namespaces.  The elpa-based packaging does not scale IMO.  Am I missing something?

**Comment by suntong** [comment]
Thanks for the reply @pierre-rouleau, I'm a elisp outsider, so I can't make any comments on the two options. 

Your option also involves putting each package in a separate directory as well, right? As long as each package is in a separate directory, I'm happy. If there's way to shorten Emacs' load-path, that'd be super. 

Again, I'm a elisp outsider, so I'd normally go with what the majority people do. 

cheers

**Comment by pierre-rouleau** [comment]
@suntong The advantage of elpa-based installation is that you can use M-x list-package to get a list of packages from Elpa-compliant web sites like GNU Elpa, MELPA and MELPA Stable, then select one you want to install and install it using the buttons in the buffer.  This also creates auto-loading calls for the important commands and variables of the packages it installs.
The disadvantage from my point of view is that it creates a new directory for each new package.  If you install over 200 packages like I have you end up with a large number of entries in Emacs load-path.  And that slows down Emacs startup time. 

I am relatively new to Emacs.  I started using it about 2 years ago.  From what I gather, before Elpa, people were copying all their Emacs Lisp files inside *one* directory and placed that directory in the load-path.  Much faster way to process.  Do you have 200 entries in your system PATH?  Nobody does (or nobody in my teams would).  I don't.  I have specialized shells with a very small number of entries in PATH (and I'v been doing this since the 80's on any OS including Windows).  Why does Emacs uses that strategy, I'm not sure yet.  Perhaps because nobody used to care about startup time since you can use an Emacs daemon.  But I care.  I almost always have multiple instances of Emacs running.  Some are short-lived, others runs for weeks.  I don't want to suffer slowdown for stuff I don't use, even if I have it on my system.

All you have to do is get a git clone of the files you need, copy the important files inside a directory somewhere (I use `~/.emacs.d/utils`), put the absolute path of that directory on Emacs `load-path` and write some code to autoload the entry points of the file you want to use and perhaps key bindings.

Take a look at the examples of init.el files I have in my [PEL system](https://github.com/pierre-rouleau/pel#readme) at  [section 2.7 of my PEL manual:  Create or Update your Emacs init.el file](https://github.com/pierre-rouleau/pel/blob/master/doc/pel-manual.rst#27create-or-update-your-emacs-initel-file).

And if you want to see how I map the origami commands in my system, use a web browser that can render PDF files in-line (like the excellent Mozilla Firefox browser) and look at my [Hide/Show/Code Folding PDF](https://raw.githubusercontent.com/pierre-rouleau/pel/master/doc/pdf/hide-show-code.pdf) which is also accessible inside the [PEL Topics PDF](https://raw.githubusercontent.com/pierre-rouleau/pel/master/doc/pdf/-index.pdf).

**Comment by suntong** [comment]
super cool!

**Comment by pierre-rouleau** [comment]
@suntong if you start using PEL and you'd like support for something that's not supported add a request via the issues in PEL.

**Pull request merged**
